"""
Export Utilities — Markdown and PDF export for reports.
"""

try:
    import markdown
except ImportError:
    markdown = None
from typing import Optional
from tools.citations import CitationTracker


def export_markdown(report_md: str, tracker: Optional[CitationTracker] = None) -> bytes:
    """
    Export report as markdown with frontmatter and citations.
    Returns bytes for download.
    """
    from datetime import datetime

    # Ensure tracker citations are in the markdown
    if tracker and tracker.citations:
        tracker_citations = tracker.format_markdown()
        if tracker_citations and tracker_citations not in report_md:
            report_md = report_md + tracker_citations

    # Build frontmatter
    frontmatter = f"""---
title: "Kimi Research Report"
topic: "{report_md.split(chr(10))[0].replace('#', '').strip() if report_md else 'Research'}"
date: "{datetime.now().isoformat()}"
generator: "Kimi Multi-Agent Research Assistant"
agents: ["Researcher", "Web Searcher", "Analyst", "Summarizer"]
---

"""

    full_md = frontmatter + report_md
    return full_md.encode("utf-8")


def export_pdf(report_md: str, tracker: Optional[CitationTracker] = None) -> bytes:
    """
    Export report as PDF using WeasyPrint.
    Returns PDF bytes for download.
    """
    try:
        from weasyprint import HTML, CSS
        from weasyprint.text.fonts import FontConfiguration
    except ImportError:
        raise RuntimeError("WeasyPrint not installed. Run: pip install weasyprint")

    # Build full HTML - ensure tracker citations are included
    if tracker and tracker.citations:
        tracker_citations = tracker.format_markdown()
        if tracker_citations and tracker_citations not in report_md:
            report_md = report_md + tracker_citations

    html_content = _build_pdf_html(report_md, tracker)

    # Create PDF
    font_config = FontConfiguration()
    html = HTML(string=html_content)
    css = CSS(string=_get_pdf_css(), font_config=font_config)

    pdf_bytes = html.write_pdf(stylesheets=[css], font_config=font_config)
    return pdf_bytes


def _build_pdf_html(report_md: str, tracker: Optional[CitationTracker]) -> str:
    """Build complete HTML document for PDF generation."""
    # Convert markdown to HTML
    md_html = markdown.markdown(
        report_md,
        extensions=["fenced_code", "tables", "toc", "attr_list", "codehilite"],
    )

    # Add citations
    citations_html = ""
    if tracker and tracker.citations:
        citations_html = "<hr>\n<h2>Sources</h2>\n<ol>\n"
        for i, (cit_id, entry) in enumerate(tracker.citations.items(), 1):
            citations_html += (
                f"<li><strong>{entry.title}</strong> — "
                f"<a href='{entry.url}'>{entry.url}</a>  \n"
                f"Relevance: {entry.relevance_pct}%</li>\n"
            )
            if entry.snippet:
                citations_html += f"<blockquote>{entry.snippet[:300]}...</blockquote>\n"
        citations_html += "</ol>"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kimi Research Report</title>
</head>
<body>
    <div class="report-container">
        <header class="report-header">
            <h1>Kimi Research Report</h1>
            <p class="meta">Generated by Kimi Multi-Agent Research Assistant</p>
        </header>
        <main class="report-body">
            {md_html}
            {citations_html}
        </main>
        <footer class="report-footer">
            <p>Generated on {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M')}</p>
        </footer>
    </div>
</body>
</html>"""


def _get_pdf_css() -> str:
    """CSS for PDF output (print-optimized)."""
    return """
@page {
    margin: 2.5cm;
    @bottom-center {
        content: "Page " counter(page);
        font-family: 'Inter', sans-serif;
        font-size: 9pt;
        color: #64748B;
    }
}

* {
    box-sizing: border-box;
}

body {
    font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    font-size: 11pt;
    line-height: 1.65;
    color: #0F172A;
    background: white;
    margin: 0;
    padding: 0;
}

.report-container {
    max-width: 100%;
}

.report-header {
    border-bottom: 2px solid #38BDF8;
    padding-bottom: 1rem;
    margin-bottom: 2rem;
}

.report-header h1 {
    font-family: 'Space Grotesk', 'Inter', sans-serif;
    font-size: 24pt;
    font-weight: 700;
    color: #0F172A;
    margin: 0 0 0.5rem 0;
}

.report-header .meta {
    color: #64748B;
    font-size: 10pt;
    margin: 0;
}

.report-body {
    font-size: 11pt;
    line-height: 1.7;
}

.report-body h1,
.report-body h2,
.report-body h3,
.report-body h4 {
    font-family: 'Space Grotesk', 'Inter', sans-serif;
    font-weight: 600;
    color: #0F172A;
    margin-top: 1.5em;
    margin-bottom: 0.5em;
    page-break-after: avoid;
}

.report-body h1 { font-size: 20pt; border-bottom: 1px solid #E2E8F0; padding-bottom: 0.3em; }
.report-body h2 { font-size: 16pt; color: #1E293B; }
.report-body h3 { font-size: 13pt; color: #334155; }
.report-body h4 { font-size: 11.5pt; color: #475569; }

.report-body p {
    margin: 0.75em 0;
    text-align: justify;
}

.report-body a {
    color: #0284C7;
    text-decoration: none;
}

.report-body a:hover {
    text-decoration: underline;
}

.report-body code {
    font-family: 'JetBrains Mono', 'Fira Code', 'Consolas', monospace;
    font-size: 0.9em;
    background: #F1F5F9;
    color: #0284C7;
    padding: 0.15em 0.4em;
    border-radius: 4px;
}

.report-body pre {
    background: #0F172A;
    color: #E2E8F0;
    padding: 1rem;
    border-radius: 8px;
    overflow-x: auto;
    page-break-inside: avoid;
}

.report-body pre code {
    background: none;
    color: inherit;
    padding: 0;
    font-size: 0.85em;
}

.report-body blockquote {
    border-left: 3px solid #38BDF8;
    padding-left: 1rem;
    margin: 1em 0;
    color: #475569;
    font-style: italic;
}

.report-body table {
    width: 100%;
    border-collapse: collapse;
    margin: 1em 0;
    font-size: 10pt;
    page-break-inside: avoid;
}

.report-body th,
.report-body td {
    border: 1px solid #E2E8F0;
    padding: 0.5em 0.75em;
    text-align: left;
}

.report-body th {
    background: #F1F5F9;
    font-weight: 600;
    font-family: 'Space Grotesk', sans-serif;
    font-size: 9pt;
}

.report-body ul,
.report-body ol {
    margin: 0.75em 0;
    padding-left: 1.5em;
}

.report-body li {
    margin: 0.4em 0;
}

.report-body hr {
    border: none;
    border-top: 1px solid #E2E8F0;
    margin: 2em 0;
}

.report-body .citation {
    color: #0284C7;
    text-decoration: none;
    border-bottom: 1px dotted #0284C7;
}

.report-footer {
    margin-top: 3rem;
    padding-top: 1rem;
    border-top: 1px solid #E2E8F0;
    text-align: center;
    color: #94A3B8;
    font-size: 9pt;
}

/* Citation references */
.report-body ol[style*="list-style-type: decimal"] {
    font-size: 10pt;
}

.report-body ol li {
    margin: 0.5em 0;
    line-height: 1.5;
}

.report-body ol li blockquote {
    margin: 0.3em 0 0 1em;
    font-size: 9pt;
    color: #64748B;
}
"""


def export_html(report_md: str, tracker: Optional[CitationTracker] = None) -> bytes:
    """Export as standalone HTML file."""
    html = _build_pdf_html(report_md, tracker)
    # Add embedded CSS
    css = _get_pdf_css()
    full_html = html.replace("</head>", f"<style>{css}</style></head>")
    return full_html.encode("utf-8")